export const Routess = {
  // pages
  LandingHomePage: { path: "/landing-page" },
  Login: { path: "/" },
  Register: { path: "/register" },

  // Under Dashboard pages
  Dashboard: { path: "/" },
  Home: { path: "/home" },
  CenterList: { path: "/center" },
  CenterDetail: { path: "/center-detail" },
  Applications: { path: "/add-application" },
  ParentsList: { path: "/parents-list" },
  ParentsDetail: { path: "/parent-details" },
  Testimonial: { path: "/testimonial-list" },
  AddTestimonial: { path: "/add-testimonial" },
  Video: { path: "/video" },
  AddVideo: { path: "/add-video" },
  KanbanBoard: { path: "/kanban-board" },
  UserApplicationForm: { path: "/application-form" },
  EditApplication: { path: "/update-application" },
  ApplicationList: { path: "application-list" },
  UpdateParents: { path: "/update-parents" },
  UpdateCenter: { path: "/update-center" },
  ApplicationFrom: { path: "/application" },
  ParentDeclaration: { path: "/parent-declaration" },
  ParentDeclarationPreview: { path: "/parent-declaration-preview" },
  UpdateDeclarationForm: { path: "/update-declaration-form" },
  ApplicationPreview: { path: "/application-preview" },
  DeclrationForm: { path: "/declration-form" },
  SetHours: { path: "/hours" },
  CategoryList: { path: "/category-list" },
  ProductList: { path: "/product-list" },
  AddProduct: { path: "/add-product" },
  AddCategory: { path: "/add-category" },
};
